### ISSUE TITLE
iOS wrapper: Cannot register custom wallet anymore

### ISSUE THREAD

**Issue by animeshworkday** [hyperledger/indy-sdk#1073]
Hello, the indy SDK 1.5 updated the custom wallet registeration call
https://github.com/hyperledger/indy-sdk/blob/78cd7625a03c7a9d64d5d63e143eeb8344d59b0d/libindy/src/api/wallet.rs#L42.

But the iOS wrapper is not updated to use the new call.
https://github.com/hyperledger/indy-sdk/blob/78cd7625a03c7a9d64d5d63e143eeb8344d59b0d/wrappers/ios/libindy-pod/Indy/Wrapper/IndyWallet.mm#L29

So that is causing the registration call to iOS wrapper to fail.

Can you please update the iOS wrapper to be in-sync with the indy sdk?

**Comment by esplinr** [comment]
@animeshworkday You closed this issue without an explanation, so for future reference we want to document here this behavior.

It is intentional that the iOS wrapper does not have a function for registering wallets. With the release of Indy SDK 1.5, we no longer allow custom wallets. Instead we support plug-able wallet back-ends that allow people to implement their own approach to storage.

Thanks for pointing out that registerWalletType was not removed as part of this change. We created an issue to track that work:
https://jira.hyperledger.org/browse/IS-904

**Comment by animeshworkday** [comment]
@esplinr I closed this ticket as I was told that the ticket should be logged in jira. 
I was registering custom wallet because I needed IndyWallet to use my implementation of IndyWalletProtocol protocol.
So now if registerType method call is gone, then how to have IndyWallet use my implementation of storage?

**Comment by vimmerru** [comment]
1. Libindy 1.5 allows efficient search of entities in wallet. It makes secure implementation of wallet protocol very complex and forces big probability of vulnerabilities in custom wallet implementations.
2. Community decided to allow usage only one wallet that is shipped with libindy. You can see corresponded accepted HIPE here: https://github.com/hyperledger/indy-hipe/blob/master/text/0013-wallets/README.md
3. Libindy walllet allows to plug different storages to cover different use cases. See HIPE and design https://github.com/hyperledger/indy-sdk/tree/master/doc/design/003-wallet-storage for details. Storage is responsible only for data access and search, but doesn't cover any encryption. 
4. In our vision storages should be implemented as plugins to libindy and not as part of applications written in application language to allow usage of storage code for applications written in different languages. See https://github.com/hyperledger/indy-sdk/tree/master/doc/design/006-cli-plugins

As result we don't have short-term plans to expose indy_register_wallet_storage as part of any wrappers interface as the most of applications will call plugin_init API provided by plugin instead of calling indy_register_wallet_storage directly. 

If you think that you still need this functionality you can create ticket in JIRA and describe your use case. We are also welcome for contribution. I suggest also consider usage of default SQLite based storage for iOS agents use cases as it was designed to cover this.

**Comment by animeshworkday** [comment]
@vimmerru I was using the custom storage in 1.4 to encrypt the data using a key that is never accessible outside the specific device. This essentially "tied" the wallet to the device.  How can I achieve that using the new design?

Few questions
1) Where does the default implementation of wallet store its data? In file? In keychain? or somewhere else
2) Can we specify the encryption key and the encryption algorithm, somehow?

**Comment by vimmerru** [comment]
> 1. Where does the default implementation of wallet store its data? In file? In keychain? or somewhere else?

- It stores data as sqlite database file inside of application storage (you can customize the place where file is stored)

> 2. Can we specify the encryption key and the encryption algorithm, somehow?

- When you create/open/delete wallet you need to provide master key or passphrase used for key derivation and the method of key derivation (raw or pwhash/argon2i with different settings). To achieve your use case you can store this key or passphrase inside of phone key chain.

**Comment by animeshworkday** [comment]
Thank you @vimmerru. I appreciate your time and help.
