### ISSUE TITLE
GettingStarted.js Error

### ISSUE THREAD

**Issue by taewooyo** [hyperledger/indy-sdk#2251]
first, I started. npm run ledger:start
After, i was running. npm run start.
But, i meet this situation.
What is error? i want to solving this.
![image](https://user-images.githubusercontent.com/66770613/96086627-90930100-0efd-11eb-8091-fad7bf239780.png)

**Comment by vp13** [comment]
Above error is because of nodejs sample code(accessing authdecryptedAliceApplyLoanKycProofJson). Replace this line 
with https://github.com/hyperledger/indy-sdk/blob/8c669cff434f5d87e7a2e2e192423c67a9df0b33/samples/nodejs/src/gettingStarted.js#L615
[ , ,authdecryptedAliceApplyLoanKycProof] = await authDecrypt(thriftWallet, thriftAliceKey, authcryptedAliceApplyLoanKycProofJson);
