### ISSUE TITLE
How to Install on Ubuntu 20.04+

### ISSUE THREAD

**Issue by radiantone** [hyperledger/indy-sdk#2284]
Current apt install directions provided no longer work.

**Comment by MySupersuit** [comment]
What error are you getting? I'm trying ["getting started"](https://hyperledger-indy.readthedocs.io/projects/sdk/en/latest/docs/getting-started/run-getting-started.html) but running into problems building with Docker using Ubuntu 20.04 on WSL2. Docker is working fine for everything else.

The problem seems to be with ipython-notebook / versioning

` Could not find a version that satisfies the requirement ipython-notebook (from versions: )
No matching distribution found for ipython-notebook
You are using pip version 8.1.1, however version 20.2.4 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.`

I had a docker problem with [another article](https://medium.com/@kctheservant/exploring-hyperledger-indy-through-indy-dev-example-10075d2547ae) using indy-dev to do with something docker which I couldn't fix - "failed to solve with frontend dockerfile.v0: failed to build LLB:" was the error
