### ISSUE TITLE
Issue building indy-sdk on ARM Mac - building for macOS-arm64 but attempting to link with file built for macOS-x86_64

### ISSUE THREAD

**Issue by DavidClawson** [hyperledger/indy-sdk#2393]
I've been following the instructions under "Mac OS" on the Readme. I have all the dependencies installed and working, I think. I run into the following error when running `cargo build`:

`ld: warning: ignoring file /usr/local/Cellar/libsodium/1.0.18_1/lib/libsodium.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
          ld: warning: ignoring file /usr/local/Cellar/zeromq/4.3.4/lib/libzmq.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
          ld: warning: ignoring file /usr/local/opt/openssl@1.1/lib/libssl.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
          ld: warning: ignoring file /usr/local/opt/openssl@1.1/lib/libcrypto.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
          Undefined symbols for architecture arm64:
            "_zmq_getsockopt", referenced from:`

I did find this on SO: [building-for-macos-x86-64-but-attempting-to-link-with-file-built-for-macos-arm64](https://stackoverflow.com/questions/65798262/building-for-macos-x86-64-but-attempting-to-link-with-file-built-for-macos-arm64)

And they said that it might be related to Apple switching the C++ compiler ARM. I'm far from an expert, but I think they said that "clang" is used (and maybe points to the preferred C compiler of the OS?) and so there might be a way to force or select which one it uses?

**Comment by georgejpadayatti** [comment]
You can solve this issue by building from Rosetta 2. In case you are trying to build explicitly for arm64 architecture then you will have to compile libssl/libsodium and other dependencies to arm64 architecture. 

You also might have to downgrade the libssl to 1.0.0 (1.1.0 is the current one) and libsodium to 18 (23 is the current one) in order to build from source in Rosetta 2.

**Comment by georgejpadayatti** [comment]
Don't mind the earlier reply. In order to solve your issue, you have to recompile the OpenSSL to arm architecture. You can do by following the below:

1. `cd ~`
2. `wget https://www.openssl.org/source/openssl-1.1.1k.tar.gz`
3. `tar -xvzf openssl-1.1.1k.tar.gz`
4. `cd openssl-1.1.1k`
5. `./Configure shared enable-rc5 zlib darwin64-arm64-cc --prefix=/usr/local/ssl --openssldir=/usr/local/ssl`
6. `make -j$(($(nproc)+1))`
7. `sudo make install`
8. `export OPENSSL_DIR=/usr/local/ssl/`
9. You can then `cd` into libindy folder
10. `cargo build`

You can now access the shared libraries from `target/debug`.

I hope this helps.

**Comment by classpjy** [comment]
ld: warning: ignoring file /usr/local/mysql/lib/libmysqlclient.21.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64 This solution is thrown when using clionide to connect to mysql
